tracking-exposed/trex

- extension/src/app.js
- extension/src/panel.js
This PR add some code to:
- hide the panel if the page is in full screen
- push the panel down if the page is in theatre mode (see the screenshot below)
- check if the extension is already loaded and clean up the DOM before add elements to avoid duplication.
The last point is to patch a bug that was caused by manually reloading the extension (I think, but few times I had all the extension event panel duplicated).
See this screenshot for what Theatre Mode is about:
> Event panel visibility

- .gitignore
- backend/lib/curly.js
featured asked by Claudio this morning, this will be useful for parser improvements and regression testing
logs raw HTML and call results of `recentVideoFetch` into `backend/logs/recentVideoFetch_<channelId>_<timeStamp>` (directory easy to change)
- html in file `raw.html`
- call result, whether success or failure, in `call.json`,
e.g., success:
```json
{
"method": "recentVideoFetch",
"channelId": "UCmHeND0P_fw8BLk8ITNzvHQ",
"success": true,
"result": [
{
"videoId": "2qrEQM-shC8",
"title": "Drone rising above See of Clouds - an Artificial Sunrise",
"urlId": "d5c5cd9a95d2e5518faa6f9d04175a49cbfbea18",
"description": "",
"recommendations": []
}
]
}
```
failure:
```json
{
"method": "recentVideoFetch",
"channelId": "UCmHeND0P_fw8BLk8ITNzvHQ",
"success": false,
"message": "Not found the …
```
> feat: log raw HTML & output of "fetchRecentVideo"

- backend/bin/server.js
- backend/lib/ycai.js
- fixed a typo in `_.some` that made adding a recommendation fail
- about removing [IGNORED_CHANNELID](https://github.com/tracking-exposed/yttrex/pull/111/commits/52025838ab6555b6addb94e2b73771baedd48e89), what is the reason to keep it? the client doesn't seem to use it and it causes 404's, if this param is needed, then maybe we can make it optional
- changed the query in "fetchRecommendationsByProfile" to what seemed logical according to the database schema, because the method was always returning an empty array. My fix might be wrong, but something is not coherent in the code.
sorry about the whitespace trimming, that's vscode doing it automatically :)
> [WIP] fix: on the way to make the recommendations work

- backend/routes/youchoose.js
this was the missing piece because the return of that method is actually validated by the model
> fix: add "url" to returned fields in "byProfile"

- backend/models/Video.ts
Video was inheriting part of its properties from Recommendation,
which made the validation fail since Recommendation has a url
and mandatory image and Video has not.
So I removed the dependency on Recommendation and instead listed
all the fields that are present in database except creatorId,
which you seem to have left out on purpose.
> fix: update Video model, removing "image" & "url"

- backend/lib/ycai.js
this null should probably not be stored in the first place,
the model expects undefined or string
this is not a full fix, but I thought that, in principle, it
may not be absurd to have some kind of filter on the database
output because we will change our schema all the time and updating
on read is a valid data-migration strategy
> [open for discussion] fix: delete recommendation description when null

- backend/bin/server.js
- backend/lib/api.js
- backend/lib/automo.js
- backend/lib/ycai.js
- backend/package.json
- backend/routes/events.js
- backend/routes/public.js
- backend/routes/statistics.js
- backend/routes/system.js
- methodology/bin/guardoni.js
In these commits you will find the definition of the command line options `--config_file, --headless, --proxy` for guardoni. Please notice that there was a little mess with some commits, check if the history is good for you.
> Added proxy, headless, config_file options as for potrex 

- backend/.dockerignore
- backend/Dockerfile
- backend/docker-compose.yml
This will let us start the API server by simply running `docker-compose up`. This can be helpful for new devs and ones not really working on API.
Cheers 🍶
> chore: fix command to start api with docker-compose

- docker-compose.yml
I realized that running `docker-compose up ycai` sets the ownership of the `YCAI/build` folder to root, to prevent this I added a sanity check in the `command` definition for the `web` service.
The other problem was the volumes bound as deps: the volume definition binds the container volume to host, so it won't work for windows users.
> fix: docker compose

- .github/workflows/backend_pull_request.yml
- .github/workflows/ycai_pull_request.yml
- .gitignore
- backend/__tests__/campaigns.spec.js
- backend/jest.config.js
- backend/package-lock.json
- backend/package.json
- backend/routes/__tests__/youchoose.e2e.ts
- backend/routes/youchoose.js
- jest.config.js
- package-lock.json
- package.json
- shared/package-lock.json
- shared/package.json
- shared/src/arbitraries/ContentCreator.arb.ts
- shared/src/arbitraries/Recommendation.arb.ts
- shared/src/arbitraries/Video.arb.ts
- shared/src/test/index.ts
- shared/tsconfig.json
I've covered with tests the main cases for the youchoose api in `backend`.
While working on this I found the [jest](https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest) extension for vscode to be really helpful.
To produce such report you need to run `npm run test -- --coverage` from the root of the project: this will output the report inside `coverage` dir. In there there's an html file you can open in your browser.
> feat: youchoose e2e

- YCAI/src/components/common/UnlinkProfileButton.tsx
- YCAI/src/components/dashboard/Dashboard.tsx
- YCAI/src/components/dashboard/LinkAccount.tsx
- YCAI/src/components/dashboard/Sidebar.tsx
- YCAI/src/components/dashboard/TokenLoginModal.tsx
- YCAI/src/i18n/en-US.ts
- YCAI/src/utils/location.utils.ts
- YCAI/typings/react-i18next/index.d.ts
This pull request removes the side-bar links during the authentication flow, and, to allow authenticating with an access token, adds a link that opens a modal with the access token input.
Closes https://github.com/tracking-exposed/yttrex/issues/216 and https://github.com/tracking-exposed/yttrex/issues/188
> feat: login flow with token

- YCAI/src/background/index.ts
- YCAI/src/components/injected/DonationOptInNudger.tsx
- YCAI/src/components/injected/YTContributionInfoBox.tsx
- YCAI/src/components/injected/YTVideoPage.tsx
- YCAI/src/components/popup/Popup.tsx
- YCAI/src/components/popup/Settings.tsx
- YCAI/src/constants/index.ts
- YCAI/src/i18n/en-US.ts
- YCAI/src/models/Messages.ts
- YCAI/src/models/Settings.ts
- YCAI/src/state/injected.commands.ts
- YCAI/src/state/injected.queries.ts
- YCAI/typings/react-i18next/index.d.ts
This features aims to politely ask users for their consent to data donation.
A notification appears in the YouChoose injected page:
It is (currently) set to appear 15 minutes after the first time YouTube is visited with the YCAI extension enabled. It will keep appearing on page reload unless "Not now" or "I agree" is clicked.
If the user clicks on "Not now", he will be reminded again after 1 week, then 2 weeks, 1 month, 2 months and then we give up.
> Nudge users into opting in to data donation

- packages/taboule/public/index.html
- packages/taboule/src/components/ErrorOverlay.tsx
- packages/taboule/src/components/Taboule.tsx
- packages/taboule/src/config.tsx
- packages/taboule/src/state/queries.ts
- packages/taboule/src/state/types.ts
- packages/taboule/tsconfig.json
- shared/src/components/Error/ErrorBoundary.tsx
- shared/src/components/Error/ErrorBox.tsx
- shared/src/endpoints/v1/public.endpoints.ts
- shared/src/endpoints/v2/index.ts
- shared/src/models/contributor/ContributorPersonalSummary.ts
- shared/src/models/http/params/PublicKey.ts
- shared/src/providers/api.provider.ts
I've defined 2 different queries for tik tok metadata that use the same API `/v1/personal/${publicKey}/summary/json` and extract `htmls` and `metadata` respectively.
This would let @SalvatoreRomano1 use Taboule in tik tok website
> fix: defined summary queries for tik tok

- .github/workflows/beta_release.yml
After releasing the `v2.0.0-beta.0` version we need to change the release command in the `beta` ci flow to avoid producing another "premajor" release on the next merge
> ci: produce only a 'prelease' in beta flow

- .github/workflows/beta_release.yml
- .github/workflows/daily_release.yml
- .github/workflows/ycai_pull_request.yml
- YCAI/.env.beta
- I've defined a workflow for the CI that deploys the dashboard on `staging.studio.youchoose.ai` when we create a PR against `daily` - once tested will be switched to "push" on daily.
> ci: ycai deploy for different envs

- .github/workflows/beta_release.yml
- .github/workflows/daily_release.yml
- YCAI/jest.config.js
- YCAI/package.json
- backend/jest.config.js
- backend/package.json
- guardoni/global-setup.js
- guardoni/jest.config.js
- guardoni/package.json
- guardoni/tsconfig.json
- jest.config.base.js
- jest.config.js
- package.json
- packages/shared/package.json
- packages/shared/tsconfig.json
- services/tktrex/shared/package.json
- tsconfig.json
- tsconfig.test.json
- yarn.lock
This PR fixes the script `yarn test` from the project's root.
Basically the `global-setup.ts` in `guardoni` was throwing because of a too opinionated server start command.
> test: fix root execution

- YCAI/src/components/dashboard/lab/RecommendationCard.tsx
- YCAI/src/components/dashboard/lab/RecommendationsLibrary/RecommendationsList.tsx
- YCAI/src/components/dashboard/lab/RecommendationsLibrary/index.tsx
- YCAI/src/state/dashboard/creator.commands.ts
- backend/bin/app.ts
- backend/routes/__tests__/youchoose.e2e.ts
- backend/routes/youchoose/deleteRecommendation.route.ts
- commitlint.config.js
- packages/shared/src/backend/errors/BackendError.ts
- packages/shared/src/backend/utils/authenticationMiddleware.ts
- packages/shared/src/backend/utils/endpoint.ts
- packages/shared/src/endpoints/v3/creator.endpoints.ts
I added an "authentication middleware" to check the existence of the authorization header to use for authenticated routes.
For now it doesn't decode the token, nor fetch the user from the db but this can be easily solved.
At the moment I don't want to overload the server with a db call for each authenticated request and we would probably end up storing the user in the `jwt` token.
> feat: delete recommendation from library

- YCAI/package.json
- yarn.lock
Removed only from `package.json` as it weren't used in the code 🎉
> chore(ycai): remove 'moment' dep

- YCAI/package.json
- guardoni/package.json
- guardoni/src/guardoni/__tests__/domainSpecific.spec.ts
- guardoni/src/guardoni/domainSpecific.ts
- t
- yarn.lock
I've removed the usage of `moment` from `guardoni` in favour of `date-fns`.
I also changed the screenshot name pattern to be consistent
> chore(guardoni): replaced `moment` with `date-fns`

- YCAI/src/components/dashboard/community/AnalyticsPage.tsx
- YCAI/src/i18n/en-US.ts
- YCAI/typings/react-i18next/index.d.ts
- backend/lib/automo.js
- packages/shared/src/models/ChannelRelated.ts
Finally the counters show real totals! 🚀
> fix(ycai): return total contributions in get creator stats api

- commitlint.config.js
- packages/shared/src/webpack/config.ts
When `DOTENV_CONFIG_PATH` is given to `webpack` it gets now resolved with the `opts.cwd` in the current config.
> chore(webpack): build dotenv config path

- YCAI/src/api.ts
- YCAI/src/app.tsx
- YCAI/src/background/index.ts
- YCAI/src/components/dashboard/Sidebar.tsx
- YCAI/src/components/dashboard/settings/AccessTokenBox.tsx
- YCAI/src/components/injected/DonationOptInNudger.tsx
- YCAI/src/components/injected/YTContributionInfoBox.tsx
- YCAI/src/components/injected/YTVideoPage.tsx
- YCAI/src/components/popup/Popup.tsx
- YCAI/src/components/popup/PopupErrorBox.tsx
- YCAI/src/components/popup/Settings.tsx
- YCAI/src/state/dashboard/creator.commands.ts
- YCAI/src/state/dashboard/creator.queries.ts
- YCAI/src/state/dashboard/public.commands.ts
- YCAI/src/state/dashboard/public.queries.ts
- YCAI/src/state/injected/injected.commands.ts
- YCAI/src/state/injected/injected.queries.ts
- YCAI/src/state/popup/popup.commands.ts
- YCAI/src/state/popup/popup.queries.ts
- backend/bin/app.ts
- backend/routes/__tests__/youchoose.e2e.ts
- backend/routes/youchoose.js
- packages/shared/src/providers/api.provider.ts
- packages/taboule/src/state/commands.ts
- packages/taboule/src/state/queries.ts
I've updated the `api.provider` to accept options with the following shape
```ts
interface GetAPIOptions {
baseURL: string;
getAuth: (req: AxiosRequestConfig) => Promise<AxiosRequestConfig>;
onUnauthorized: (res: AxiosResponse) => Promise<AxiosResponse>;
}
```
in order to connect the authentication with the api responses.
I also splitted the clients between "authenticated" and "public"
> Fix(ycai): unauthorized request triggers a content creator logout

- YCAI/src/components/dashboard/Sidebar.tsx
Version added under the logo with the feedback of @spaghettinucleari
> fix(ycai): show version and build time in dashboard

- backend/lib/automo.js
I've fixed the issue was having @margelacool last week by excluding channels with "authorName" equal to `null` to be returned.
> fix(ycai): content creator related with no nullable 'recommendedSource'

- packages/shared/src/models/ChannelRelated.ts
- packages/taboule/src/config/index.tsx
This is meant to be a temporary fix till we wait for the deploy of yttrex API v2.5
> fix(ycai): channel related id patch

- platforms/ecosystem.config.js
I've defined a single entrypoint to launch all the platforms services in one command: `yarn pm2 platforms/ecosystem.config.js`
> chore: pm2 all platforms

- platforms/guardoni/__tests__/cli.spec.ts
- platforms/guardoni/__tests__/guardoni/guardoni.spec.ts
- platforms/guardoni/src/electron/app/App.tsx
- platforms/guardoni/src/electron/app/Header.tsx
- platforms/guardoni/src/electron/app/components/ExperimentExecution.tsx
- platforms/guardoni/src/electron/app/components/ExperimentList.tsx
- platforms/guardoni/src/electron/app/modals/AddProfileModal.tsx
- platforms/guardoni/src/electron/app/modals/AdvancedSettingModal.tsx
- platforms/guardoni/src/electron/events/renderer.events.ts
- platforms/guardoni/src/electron/main.ts
- platforms/guardoni/src/guardoni/browser.ts
- platforms/guardoni/src/guardoni/config.ts
- platforms/guardoni/src/guardoni/constants.ts
- platforms/guardoni/src/guardoni/guardoni.ts
- platforms/guardoni/src/guardoni/profile.ts
- platforms/guardoni/src/guardoni/types.ts
- platforms/yttrex/extension/webpack.config.ts
The UI profile selection now works and the profile is correctly retrieved on the following runs.
I also added a link for the experiment id in the execution page as @vecna asked, but I'll wait to check this with @spaghettinucleari before merging
> fix(guardoni): profile loading, selection and creation, closes #518

- packages/shared/src/extension/chrome/background/account.ts
- platforms/tktrex/extension/src/AppEnv.ts
- platforms/yttrex/extension/webpack.config.ts
With this PR is possible to build an extension with specific `publicKey` and `secreteKey` with:
```sh
PUBLIC_KEY=XXX SECRET_KEY=XXX yarn yt:ext build
PUBLIC_KEY=XXX SECRET_KEY=XXX yarn tk:ext build
```
> chore: use publicKey and secretKey from process.env in extension

- platforms/guardoni/src/guardoni/extension.ts
This will prevent my manual edit of the release assets names to make them downloadable by guardoni.
> fix(guardoni): extension url template aligned with extension zip file names

- platforms/guardoni/tsconfig.json
- platforms/tktrex/tt-automate/package.json
- platforms/tktrex/tt-automate/src/experiment/index.ts
- platforms/tktrex/tt-automate/src/platform/TikTok/util/page.ts
- platforms/tktrex/tt-automate/src/platform/TikTok/util/project.ts
- platforms/tktrex/tt-automate/src/util/page.ts
- platforms/tktrex/tt-automate/tsconfig.json
By removing the `puppeteer` dependency and using `puppeteer-extra` and `puppeteer-core` we should get rid of the local chromium version downloaded automatically by the package and rely only on the paths available on the user machine - like we do for production.
> chore: remove puppeteer from tx-automation

- .github/workflows/guardoni_pull_request.yml
- packages/shared/src/providers/puppeteer/DirectiveHook.ts
- platforms/guardoni/docs/development/test.md
- platforms/guardoni/package.json
- platforms/guardoni/scripts/cli-yt-test-home.mjs
- platforms/guardoni/scripts/cli-yt-test-videos.mjs
- platforms/guardoni/src/guardoni/browser.ts
- platforms/guardoni/src/guardoni/cli.ts
- platforms/guardoni/src/guardoni/directives/yt.directives.ts
- platforms/guardoni/src/guardoni/guardoni.ts
- platforms/guardoni/src/guardoni/types.ts
This is the integration of the API for metadata ( #552 ) in guardoni, to be able to fetch the experiment results after execution.
This will enable @chobeat to proceed with Mbuto integration
> fix(guardoni): fetch metadata after experiment in cli tests

- platforms/guardoni/guardoni.config.json
- platforms/guardoni/src/guardoni/cli.ts
- platforms/guardoni/src/guardoni/config.ts
- platforms/guardoni/src/guardoni/guardoni.ts
Here I fixed a couple of small issues in guardoni:
- check if `hooks.custom.cookieModal` exists before calling it during "navigate"
- correct platform frontend's config computation
- additional config for `yt-navigate` and `tk-navigate` to override the `headless` option
> fix(guardoni): cli navigation and platform's frontend assignment

- platforms/yttrex/backend/parsers/searches.ts
I "fixed" the ts compilation error by setting to `any` the return type for the search parser function.
> fix(yttrex): parser search loosly typings

- platforms/guardoni/docs/cli/usage.md
- platforms/guardoni/src/guardoni/cli.ts
- platforms/guardoni/src/guardoni/experiment.ts
- platforms/guardoni/src/guardoni/extension.ts
- platforms/guardoni/src/guardoni/guardoni.ts
- platforms/guardoni/src/guardoni/profile.ts
In order to download updated version of the extension we need to clear the directory where guardoni stores the extension.
Here's an handy command to achieve this: `guardoni-cli yt-clean` (or `guardoni-cli tk-clean`)
> fix(guardoni): delete extension cache

- packages/shared/src/models/Step.ts
- packages/shared/src/providers/puppeteer/StepHooks.ts
- packages/shared/src/providers/puppeteer/puppeteer.provider.ts
- packages/shared/src/providers/puppeteer/steps/click.ts
- packages/shared/src/providers/puppeteer/steps/keyPress.ts
- packages/shared/src/providers/puppeteer/steps/openURL.ts
- packages/shared/src/providers/puppeteer/steps/scroll.ts
- platforms/guardoni/src/electron/tabs/FromURLsTab.tsx
- platforms/guardoni/src/guardoni/experiment.ts
- platforms/guardoni/src/guardoni/guardoni.ts
- platforms/guardoni/src/guardoni/steps/tk.steps.ts
This PR adds the possibility to define an additional column in the experiment csv named `onCompleted`.
The value given to this column is - possibly - a concatenation of actions which are, for now, `keypress` and `click`:
- `keypress(ArrowDown;5;5000)`: press `ArrowDown` with `5000`ms of delay for `5` times
- `click(video;0)`: click element by selector `video` with delay `0`ms
The concatenation can be achieved by using the delimiter ` - `, i.e. `click(.my-button;0) - keypress(ArrowUp;1;1000) - click(video;1000)`
The syntax of this command use the `;` as separator cause the `,` would break the csv - but it can be discussed.
Here's a sample csv you can you to test it:
```csv
url,urltag,loadFor,watchFor,type,incrementScrollByPX,totalScroll,onCompleted …
```
> fix(shared): defined puppeteer hooks for keypress and click

- packages/shared/src/providers/__tests__/parser.provider.spec.ts
- packages/shared/src/providers/parser.provider.ts
- packages/shared/src/test/utils/parser.utils.ts
- platforms/tktrex/backend/bin/parser.ts
- platforms/tktrex/backend/parsers/__tests__/native.e2e.ts
- platforms/tktrex/backend/parsers/config.ts
- platforms/tktrex/backend/parsers/downloader.ts
- platforms/tktrex/backend/parsers/metrics.ts
- platforms/tktrex/backend/parsers/native.ts
- platforms/tktrex/backend/parsers/nature.ts
- platforms/tktrex/backend/parsers/shared.ts
- platforms/tktrex/backend/routes/__tests__/personal.e2e.ts
- platforms/yttrex/backend/bin/leaves-parser.ts
- platforms/yttrex/backend/bin/parser.ts
- platforms/yttrex/backend/parsers/config.ts
- platforms/yttrex/backend/parsers/home.ts
- platforms/yttrex/backend/parsers/leaf.ts
- platforms/yttrex/backend/parsers/nature.ts
- platforms/yttrex/backend/parsers/searches.ts
- platforms/yttrex/backend/parsers/thumbnail.ts
- platforms/yttrex/backend/parsers/video.ts
- platforms/yttrex/backend/routes/__tests__/personal.e2e.ts
I added another field to pass to the `GetParserProvider` named `config` that is passed down to the `ParserFn`.
In this way we can pass from the outside variables like `nconf.get('downloads')` to change the parser behavior.
> refactor(shared): parser provider compatible with browser environment

- .github/workflows/daily_release.yml
- scripts/install-from-shrinkzip.sh
- scripts/shrink.sh
I fixed the `zip` creation for extension review submission by including the `yarn.lock` in the output.
I also defined a step in the CI to test this flow everytime we merge on daily.
🎉
> chore(workspace): extension reviewer install from zip and build flow

- packages/shared/src/extension/app.ts
- packages/shared/src/extension/utils/HTMLSize.utils.ts
- platforms/yttrex/backend/__tests__/parser/html/parseVideo.e2e.ts
- platforms/yttrex/backend/lib/utils.js
- platforms/yttrex/backend/routes/events.js
- platforms/yttrex/extension/src/app/app.ts
- platforms/yttrex/shared/src/models/Nature.ts
- platforms/yttrex/shared/src/parser/parsers/nature.ts
- platforms/yttrex/shared/src/parser/parsers/uxlang.js
- platforms/yttrex/shared/src/parser/parsers/video.ts
Improved the yt video parsing with:
- check for `title` and `author` info existence for the data contribution before sending
- prevent parsing failure when `likes` info not available
> fix(yt:shared): search, home and video route handlers

- platforms/yttrex/backend/routes/__tests__/metadata.e2e.ts
- platforms/yttrex/backend/routes/metadata.ts
- platforms/yttrex/shared/src/endpoints/v2/metadata.endpoints.ts
- platforms/yttrex/shared/src/models/Nature.ts
This PR improved the `GET /api/v2/metadata` api, by always require the `publicKey` query param and accept the `nature` one to filter results.
Taboule can then benefit from this API for showing data for `home`, `search`, `video` and `profile` nature
> fix(yt:backend): metadata api filter by nature

- scripts/cloc.sh
The script in `scripts/cloc.sh` outputs a table with lines-of-code-per-language, i.e.:
```
./platforms/yttrex/backend
1370 text files.
801 unique files.                                          
615 files ignored.
github.com/AlDanial/cloc v 1.90  T=1.27 s (625.2 files/s, 210716.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                           155              2              0         122863
JavaScript                      55            890            690         109201
HTML                           534           5169              0          24932
TypeScript …
```
> chore(workspace): defined 'cloc' script to track ts refactor progress

- platforms/tktrex/backend/ecosystem.config.js
- platforms/tktrex/backend/ecosystem.dev.config.js
- platforms/yttrex/backend/ecosystem.config.js
- platforms/yttrex/backend/ecosystem.dev.config.js
Enable [debug](https://github.com/debug-js/debug#environment-variables) colors for `pm2 logs`
> chore(workspace): use debug colors in pm2 logs

- .github/workflows/guardoni_pull_request.yml
- packages/shared/src/providers/puppeteer/steps/click.ts
- packages/shared/src/providers/puppeteer/steps/keyPress.ts
- packages/shared/src/utils/csv.utils.ts
- packages/shared/src/utils/task.utils.ts
- platforms/guardoni/__tests__/cli/cli-tk.spec.ts
- platforms/guardoni/__tests__/cli/cli-yt.spec.ts
- platforms/guardoni/experiments/tk-on-completed-hooks.csv
- platforms/guardoni/jest.config.js
- platforms/guardoni/package.json
- platforms/guardoni/src/electron/events/renderer.events.ts
- platforms/guardoni/src/guardoni/__tests__/experiment.spec.ts
- platforms/guardoni/src/guardoni/experiment.ts
- platforms/guardoni/test/index.ts
- platforms/guardoni/test/writeExperimentCSV.ts
- platforms/guardoni/tsconfig.json
- platforms/tktrex/backend/lib/CSV.ts
This PR will enable to delimit _hooks_ in experiments with either `-` or `–` and prevent hooks parsing error from happening again.
> fix(guardoni): expect '–' char as valid delimiter for `onCompleted` column

- platforms/yttrex/backend/lib/automo.ts
I've found this bug while running `./scripts/cli-test-from-fixtures.mjs yt video 5` from `./platforms/guardoni`.
The data collection and the filtering seems to work fine.
> fix(yt:backend): return 'steps' when creating experiment

- platforms/yttrex/extension/src/popup.tsx
UI for setting the `experimentId` was enabled only for `NODE_ENV=development` in `yt:ext`
> fix(yt:ext): enabled experimentId UI in popup

- packages/shared/src/utils/fp.utils.ts
- platforms/tktrex/backend/config/settings.json
- platforms/tktrex/backend/models/APIRequest.ts
- platforms/tktrex/backend/routes/__tests__/events.e2e.ts
- platforms/tktrex/backend/routes/__tests__/personal.e2e.ts
- platforms/tktrex/backend/routes/events.ts
- platforms/tktrex/backend/scripts/build-indexes.js
- platforms/tktrex/extension/__tests__/app.spec.ts
- platforms/tktrex/extension/__tests__/profile.spec.ts
- platforms/tktrex/extension/src/background/api.ts
- platforms/tktrex/shared/src/arbitraries/APIRequestContributionEvent.arb.ts
- platforms/tktrex/shared/src/arbitraries/ContributionEvent.arb.ts
- platforms/tktrex/shared/src/endpoints/v2/public.endpoints.ts
- platforms/tktrex/shared/src/helpers/uniqueId.ts
- platforms/tktrex/shared/src/models/apiRequest/APIRequest.ts
- platforms/tktrex/shared/src/models/apiRequest/APIRequestContributionEvent.ts
- platforms/tktrex/shared/src/models/apiRequest/index.ts
- platforms/tktrex/shared/src/models/events/ContributionEvent.ts
- platforms/tktrex/shared/src/models/http/TKHeaders.ts
- platforms/tktrex/shared/src/models/http/index.ts
- platforms/tktrex/shared/src/models/http/query/ListAPIRequest.query.ts
- platforms/tktrex/shared/src/models/http/query/ListQueryBase.query.ts
- platforms/tktrex/shared/src/models/http/query/index.ts
- platforms/tktrex/shared/src/models/index.ts
I've defined the implementation for `POST /api/v2/apiEvents` and it:
- receives and accepts new event of `type: "api"` - mixed events can be sent but they get discarded at the moment
- validates the `headers`
- saves the event in the `apiRequests` collection
I also defined the _indexes_ for the collection in the proper file.
> feat(tk:backend): validate and save contribution events of type 'api'

- packages/shared/src/components/Error/ErrorBox.tsx
- platforms/guardoni/__tests__/cli/cli-yt.spec.ts
- platforms/guardoni/jest.setup.js
- platforms/guardoni/scripts/cli-test-from-fixtures.mjs
- platforms/guardoni/src/guardoni/__tests__/experiment.spec.ts
- platforms/guardoni/src/guardoni/cli.ts
- platforms/guardoni/src/guardoni/experiment.ts
- platforms/guardoni/src/guardoni/guardoni.ts
- platforms/guardoni/src/guardoni/types.ts
- platforms/guardoni/test/index.ts
- platforms/storybook/src/stories/ErrorModal.stories.tsx
- platforms/tktrex/backend/lib/automo.ts
- platforms/tktrex/shared/src/endpoints/v2/public.endpoints.ts
- platforms/tktrex/shared/src/models/http/query/ListMetadata.query.ts
- platforms/ycai/studio/src/background/index.ts
- platforms/yttrex/shared/src/models/http/metadata/query/ListMetadata.query.ts
This one close #810.
I've added the guardoni command to download metadata, apiRequests and sigiState json files.
The test plan is described in #811
> feat(guardoni): defined command to download experiment results

- packages/shared/src/providers/api.provider.ts
- platforms/guardoni/src/guardoni/cli.ts
- platforms/guardoni/src/guardoni/experiment.ts
The `experimentId` parameter for `tk-download` wasn't passed properly, this made the command returning all possible datas from `metadata`, `apiRequests` and `sigiStates` collections
> fix(guardoni): experimentId parameter for download command

- platforms/tktrex/backend/bin/app.ts
```
docker-compose up -d mongodb
docker-compose up -d mongo-tk-indexes
docker-compose up -d mongo-yt-indexes
yarn tk:backend build
yarn yt:backend build
yarn guardoni build:cli
cd platforms/guardoni
yarn cli tk-list
yarn cli yt-list
```
> fix(tk:backend): remove redundant occurrence of 'api' from GET /api/v2/directives/public endpoint

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
I'm adding some initial templates for issues and PRs to standardize the info we provide as input (issues) and as output (PR).
For the issue I have only defined a template for `bug` report and left the possibility to create them from a blank template.
The PR template is this one I'm using.
[workspace] defined bug report and PR template [skip ci]
[Github says](https://github.com/tracking-exposed/trex/blob/ef444117c9b794e9f52b4804f25017c3825baac6/.github/ISSUE_TEMPLATE/bug-report.yml) it is using the bug report as template for issues.
> chore(workspace): defined issue template [skip ci]

- packages/shared/src/extension/popup/components/Settings.tsx
Removed experiment id Field when it's not present and made it not editable when it is.
> feat(shared): remove experiment id field when its unset

- .husky/pre-push
- README.md
- packages/shared/src/backend/scripts/clean-test-db.ts
- platforms/tktrex/backend/package.json
- platforms/tktrex/backend/scripts/clean-test-db.ts
- platforms/yttrex/backend/__tests__/parser/html/parseSearch.e2e.ts
- platforms/yttrex/backend/package.json
- platforms/yttrex/backend/scripts/clean-test-db.ts
- scripts/build.sh
This `hook` enforces to run `yarn build` (commented out at the moment cause `docs` aren't building) and `yarn test` before pushing, adding ~6 min to the time needed for push
With this in place we should have a better flow to be sure we're not pushing "wrong code", but it can be easily disable with `-n` at any occurrence
> chore(workspace): pre-push hook

- docs/docs/partials/extension/_development.mdx
- docs/src/css/custom.css
- platforms/yttrex/docs/docs/backend.md
- platforms/yttrex/docs/docs/enviroment.mdx
- platforms/yttrex/docs/docs/intro.md
- platforms/yttrex/docs/docs/markdown-styles.module.css
PR intended to write a better documentation for the project.
To run it in dev mode run the following commands from the root folder:
`./docs/scripts/build.sh`
`yarn docs start`
and visit: http://localhost:3000/yttrex/docs/extension and http://localhost:3000/yttrex/docs/backend
> docs(yt:ext): docs extension improvements

- platforms/yttrex/backend/lib/parser/html.ts
This solves a bug on `yt:parser` (and potentially `tk:parser`) where the _metadata_ upsert failed for having `_id` in the update payload.
fix(shared): omit '_id' field from metadata when upsert from parsing
```sh
docker-compose up -d mongo-yt-indexes
yarn pm2 start platforms/yttrex/backend/ecosystem.dev.config.js
yarn yt:ext watch
yarn pm2 logs
[...]
```
Load the extension in your browser and navigate in YT, you should have no errors.
> fix(shared): omit '_id' field from metadata when upsert from parsing
