tracking-exposed/trex

backend/sections/analysis.pug
backend/sections/api.pug
backend/sections/data.pug
backend/sections/index.pug

As per title.
Some notes:
`backend/sections/analysis.pug`
77. It is not clear what's meant by the second sentence
`backend/sections/data.pug`
74. Second sentence is unclear

Fixed typos, grammar mistakes and made some points clearer

---

backend/parsers/longlabel.js
backend/parsers/video.js
backend/scripts/wetest1-basic.js
backend/tests/lib/longlabel.js

contains longlabel super parsing (work in progress)

Only mongo3

---

backend/endpoints/v3/creator.endpoints.ts

This reverts commit ad86b4d3b2b4f431036b2a43f90a4b8256af9e4f.

revert: "fix: register creator output codec"

---

backend/models/Recommendation.ts

Anybody see a problem with that? Haven't done much testing.

[WIP] fix: add url & make image mandatory in reco model

---

backend/endpoints/index.ts
backend/endpoints/v1/index.ts
backend/endpoints/v2/index.ts
backend/endpoints/v3/index.ts
backend/routes/public.js
backend/routes/youchoose.js

@ascariandrea is this helpful ? should I merge it?

fix: standardized endpoints version exports

---

backend/endpoints/v2/index.ts
backend/models/ContributionEvent.ts

Correct the definition for `VideoContributionEvent` and added `ADVContributionEvent`.
**N.B.** merge after #124

fix: data donation models

---

backend/bin/server.js
backend/lib/api.js
backend/lib/ycai.js
backend/routes/youchoose.js

refactor: generalized the authentication function

---

.dockerignore
.gitignore
Dockerfile
YCAI/.env
YCAI/.env.production
YCAI/jest.setup.js
YCAI/src/components/dashboard/settings/Swagger.tsx
YCAI/src/components/popup/Popup.tsx
YCAI/src/config.ts
YCAI/src/i18n/en-US.ts
YCAI/src/providers/api.provider.ts
YCAI/src/providers/dataDonation.provider.ts
YCAI/src/state/creator.queries.ts
YCAI/src/utils/logger.utils.ts
YCAI/webpack.config.js
backend/.dockerignore
backend/Dockerfile
backend/tsconfig.json
docker-compose.yml
shared/package-lock.json
shared/package.json
shared/tsconfig.json

With this PR we will be able to start the stack and start `ycai` extension development with only `docker-compose up ycai`.
I hope this will simplify a lot the DevX to start contributing on the extension.
To test run:
- `docker-compose build`
- `docker-compose up ycai`

fix: docker compose

---

YCAI/src/providers/api.provider.ts
YCAI/src/state/creator.queries.ts
backend/bin/server.js
backend/routes/ads.js
package.json
shared/package.json
shared/src/endpoints/v2/index.ts
shared/src/endpoints/v3/creator.endpoints.ts
shared/src/models/stats/ChannelADV.ts

I tested the API, but I didn't attached the endpoints

implemented requested fixes on channel advertisement

---

YCAI/src/components/dashboard/community/AnalyticsPage.tsx
YCAI/src/components/dashboard/community/DonutChart.tsx

fix: recommendability score style

---

YCAI/src/components/common/StatsCard.tsx
YCAI/src/components/dashboard/community/ADVChannelStatsBox.tsx
YCAI/src/components/dashboard/community/AnalyticsPage.tsx
YCAI/src/i18n/en-US.ts
YCAI/typings/react-i18next/index.d.ts
shared/src/models/ContentCreator.ts
shared/src/models/CreatorStats.ts
shared/src/utils/number.utils.ts
shared/tsconfig.json

I didn't address the style for the related channels here, but I fixed the "StatsCard" to display meaningful counts of:
- total recommendations analyzed
- portion of recommendations coming from other channels
and make the style more similar to mockup

fix: analytics UI

---

packages/taboule/src/components/Taboule.tsx
packages/taboule/src/config/index.tsx

Taboule cells have now a default width of `200`

fix: column default width

---

YCAI/.env
YCAI/src/components/dashboard/LinkAccount.tsx

this PR should fix the new endpoint. I also changed an URL that should consider the baseURL instead of the absolute one, because it should also work on staging and beta domains

fix: changed default YCAI url

---

YCAI/src/components/dashboard/lab/VideoCard.tsx

The issue is still present locally, but this is a "default" value that shouldn't affect negatively the current behavior.
Let's see if it works on staging!

fix: defined refer policy for video card image

---

YCAI/package.json
YCAI/src/components/dashboard/community/AnalyticsPage.tsx
YCAI/src/i18n/en-US.ts
YCAI/tsconfig.json
packages/taboule/src/components/Taboule.tsx
packages/taboule/src/config/index.tsx
packages/taboule/src/config/params.ts
packages/taboule/tsconfig.json

I fixed the issues reported in #332 except the label of metadata/recommendations cause we need a new property returned from the api.

fix: ycai minor bugs

---

.github/workflows/backend_pull_request.yml
.github/workflows/extension_pull_request.yml
.github/workflows/guardoni_pull_request.yml
.github/workflows/taboule_pull_request.yml
.github/workflows/ycai_pull_request.yml
YCAI/src/components/common/YTVideo.tsx
YCAI/src/components/dashboard/Dashboard.tsx
YCAI/src/components/dashboard/Sidebar.tsx
YCAI/src/components/dashboard/__tests__/Dashboard.spec.tsx
YCAI/src/components/dashboard/lab/AddRecommendationBox.tsx
YCAI/src/components/dashboard/lab/LabVideoEdit.tsx
YCAI/src/components/dashboard/lab/LabVideoEdit/VideoRecommendations.tsx
YCAI/src/components/dashboard/lab/LabVideoEdit/index.tsx
YCAI/src/components/dashboard/lab/RecommendationsLibrary/RecommendationsList.tsx
YCAI/src/components/dashboard/lab/RecommendationsLibrary/index.tsx
YCAI/src/i18n/en-US.ts
YCAI/src/utils/location.utils.ts
YCAI/typings/react-i18next/index.d.ts

I added the recommendations library page at `/lab/recommendations` with existing components.
The API for listing and create recommendations works fine 🎉

feat: recommendations library page

---

backend/config/trexstats.json
backend/lib/automo.js
backend/lib/cache.js
backend/parsers/longlabel.js
backend/parsers/searches.js
backend/parsers/thumbnail.js
backend/routes/personal.js
backend/routes/statistics.js
backend/scripts/build-indexes.js

this
* fixes search parsers
* supports chinese interface parsing (still w.i.p.)

parser search fix and enhancement to support chinese language

---

YCAI/src/components/dashboard/Dashboard.tsx
YCAI/src/components/dashboard/LinkAccount.tsx
YCAI/src/components/dashboard/account/congrats/index.tsx
YCAI/src/components/dashboard/lab/RecommendationsLibrary/RecommendationsList.tsx
YCAI/src/i18n/en-US.ts
YCAI/src/state/dashboard/creator.commands.ts
YCAI/src/state/dashboard/creator.queries.ts
YCAI/typings/react-i18next/index.d.ts

fix(ycai): account linked congrats screen

---

YCAI/src/components/common/Image.tsx
YCAI/src/components/dashboard/lab/EditRecommendation.tsx
YCAI/src/components/dashboard/lab/RecommendationCard.tsx
YCAI/src/components/dashboard/lab/RecommendationCardLibrary.tsx
YCAI/src/components/injected/InjectedRecommendationCard.tsx
backend/lib/ycai.js
packages/shared/src/models/Recommendation.ts

fix(ycai): recommendation card placeholder

---

YCAI/src/components/dashboard/Sidebar.tsx
YCAI/src/i18n/en-US.ts
YCAI/typings/react-i18next/index.d.ts

fix(ycai): menu with sub items in dashboard sidebar

---

YCAI/src/components/buttons/DeleteGemButton.tsx
YCAI/src/components/dashboard/Dashboard.tsx
YCAI/src/components/dashboard/lab/EditRecommendation.tsx
YCAI/src/components/dashboard/lab/GemLibrary/GemCard.tsx
YCAI/src/components/dashboard/lab/GemLibrary/GemList.tsx
YCAI/src/components/dashboard/lab/GemLibrary/index.tsx
YCAI/src/components/dashboard/lab/LabVideoEdit/RecommendationCard.tsx
YCAI/src/components/dashboard/lab/LabVideoEdit/VideoRecommendations.tsx
YCAI/src/components/dialogs/DeleteGemConfirmDialog.tsx
YCAI/src/i18n/en-US.ts
YCAI/src/state/dashboard/creator.commands.ts
YCAI/typings/react-i18next/index.d.ts
backend/lib/ycai.js

fix(ycai): added delete and edit dialogs for gems in library

---

platforms/guardoni/src/electron/app/components/ExperimentExecution.tsx
platforms/guardoni/src/electron/app/components/ExperimentList.tsx
platforms/guardoni/src/electron/app/components/OutputPanel.tsx

style: experiment execution page

---

.github/workflows/guardoni_pull_request.yml
packages/shared/src/arbitraries/Directive.arb.ts
packages/shared/src/models/Directive.ts
packages/shared/src/models/Experiment.ts
packages/shared/src/models/index.ts
packages/shared/src/providers/swagger/IOTSToOpenAPISchema.ts
platforms/guardoni/__tests__/cli.spec.ts
platforms/guardoni/__tests__/guardoni/guardoni.spec.ts
platforms/guardoni/experiments/tk-videos.csv
platforms/guardoni/scripts/cli-tk-test.sh
platforms/guardoni/scripts/cli-yt-test.sh
platforms/guardoni/src/electron/events/renderer.events.ts
platforms/guardoni/src/electron/tabs/FromCSVFileTab.tsx
platforms/guardoni/src/guardoni/browser.ts
platforms/guardoni/src/guardoni/cli.ts
platforms/guardoni/src/guardoni/experiment.ts
platforms/guardoni/src/guardoni/guardoni.ts
platforms/guardoni/src/guardoni/types.ts
platforms/guardoni/tsconfig.json
platforms/tktrex/shared/src/arbitraries/SearchDirective.arb.ts
platforms/tktrex/shared/src/models/directive/SearchDirective.ts
platforms/yttrex/shared/src/arbitraries/ComparisonDirective.arb.ts
platforms/yttrex/shared/src/models/Directive.ts

You can easily test this by running:
```sh
cd ./platforms/guardoni
./scripts/cli-build.sh
./scripts/cli-tk-test.sh
```
**There's a step in the `cli-tk-test.sh` that opens the browser to let you perform a login on the tiktok platform, but the script fails when you close the browser. Comment it out after you login and rerun the script**

fix: guardoni tiktok csv

---

packages/shared/src/extension/app.ts
platforms/tktrex/backend/lib/parserchain.js
platforms/tktrex/backend/lib/utils.js
platforms/tktrex/backend/parsers/profile.js
platforms/tktrex/backend/parsers/shared.js
platforms/tktrex/backend/routes/events.js
platforms/tktrex/backend/routes/personal.js
platforms/tktrex/backend/routes/search.js
platforms/tktrex/extension/__tests__/htmls/tk-profile.html
platforms/tktrex/extension/__tests__/profile.spec.ts
platforms/tktrex/extension/src/app/app.ts
platforms/tktrex/extension/src/app/handlers.ts
platforms/tktrex/extension/src/handlers.ts
platforms/tktrex/extension/src/interceptor/index.ts
platforms/tktrex/extension/src/models/HubEvent.ts

This is the implementation of #501

feat: tiktok profile scraper 

---

platforms/tktrex/extension/public/manifest.json
platforms/ycai/studio/public/manifest.json

Removed the `alarms` permissions from every extensions' `manifest.json`

fix: remove alarms permission

---

packages/shared/src/models/HandshakeBody.ts
platforms/guardoni/__tests__/cli/cli-yt.spec.ts
platforms/guardoni/bin/check-stealth.ts
platforms/guardoni/src/guardoni/experiment.ts
platforms/guardoni/src/guardoni/guardoni.ts
platforms/guardoni/src/guardoni/profile.ts
platforms/guardoni/src/guardoni/types.ts
platforms/tktrex/extension/__tests__/app.spec.ts
platforms/tktrex/extension/__tests__/profile.spec.ts
platforms/yttrex/extension/__tests__/app.spec.ts
platforms/yttrex/extension/src/app/index.ts

fix: removed "newProfile" in favour of "execount" to keep track of profile usage counting

---

packages/shared/src/extension/chrome/popup/components/popup.tsx
packages/shared/src/extension/chrome/popup/components/settings.tsx

I've added here a new UI block that shows a message and a link to tiktok when the app isn't initialized.

fix(tktrex): show an handy message in the popup when extension is not yet bootstrapped

---

platforms/tktrex/backend/lib/utils.js
platforms/tktrex/backend/routes/__tests__/events.e2e.ts
platforms/tktrex/backend/routes/events.js

Notes:
* `-lib:utils:hash` when `DEBUG=*` might help and should be the default

fix(tktrex): Clarify hashing logic and sequence, embedded Nature as part of the fields selection

---

packages/shared/src/backend/index.ts
platforms/tktrex/backend/bin/app.ts
platforms/tktrex/backend/bin/server.ts
platforms/yttrex/backend/bin/app.ts
platforms/yttrex/backend/bin/server.ts

Added general definition for `/v0/health` route and check `mongo` connection for a successful response.

fix(yt:backend): defined /v0/health endpoint

---

scripts/cloc.sh

The output of `cloc` is now more readable as it is grouped by `file` and than `lang`
```
./packages/shared/src
100 files
128 text files.
classified 128 files
Duplicate file check 128 files (123 known unique)
Unique:      100 files                                          
128 unique files.                              
Counting:  100
2 files ignored.
github.com/AlDanial/cloc v 1.90  T=0.05 s (2526.9 files/s, 221857.3 lines/s)
-------------------------------------------------------------------------------------------------------------------------
File                                                                                  blank        comment           code
------------------------------------------------------------------------------------------------------------------------- …
```

chore(workspace): cloc script grouping by file and by lang

---

platforms/tktrex/backend/config/settings.json
platforms/tktrex/backend/config/trexstats.json
platforms/tktrex/backend/routes/emails.js
platforms/tktrex/backend/scripts/build-indexes.js
platforms/yttrex/backend/scripts/build-indexes.js

because of migration opportunity and because the `experimentId` has changed concept during the time, a few collections in our mongodb needs some review.
This PR propose few changes and we can discuss, based on the currently used query and data model, if some fields are outdated.

fix: polish mongo indexes

---

packages/shared/src/extension/__tests__/HTMLSize.spec.ts
packages/shared/src/extension/utils/HTMLSize.utils.ts
platforms/tktrex/extension/src/app/app.ts
platforms/yttrex/extension/src/app/app.ts

```sh
yarn shared test HTMLSize
```

test(shared): ensure HTMLSize module can compute size correctly

---

platforms/storybook/.storybook/main.js
platforms/tktrex/extension/jest.setup.ts
platforms/ycai/studio/jest.setup.js
platforms/ycai/studio/src/config.ts
platforms/yttrex/extension/jest.setup.ts

Using regEx to remove the ms from BUILD_DATE environment variables.

feat(shared): remove ms from BUILD_DATE env vars

---

.github/workflows/beta_pull_request.yml
.github/workflows/daily_release.yml
.github/workflows/master_release.yml

Since we changed the hosting for `youchoose.ai` - and we're gonna migrate soon to _docker_ - I have disabled the deploy from the CI for `ycai`.
ycai: disable deploy with rsync strategy
When merging this on `daily` the CI should run without errors.

ci(ycai): disable deployment with rsync, close #842

---

.github/workflows/build_from_zip.yml
docker-compose.yml
from-zip.Dockerfile
scripts/shrink.sh

```sh
docker-compose build build-from-zip
docker-compose run build-from-zip
yarn
yarn shared build
yarn tk:ext dist
yarn yt:ext dist
yarn ycai build
```

build(workspace): interactive "from-zip" docker container
